In [16]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

In [17]:
GRAPH_DIR = Path(
    r"D:/Kanishka/@inventing/codinggg/Languages/Python/DVP/DVP Website+Presentation/EV-Population-Insights/website/graphs"
)

GRAPH_DIR.mkdir(parents=True, exist_ok=True)

In [18]:
path = r"D:/Kanishka/@inventing/codinggg/Languages/Python/DVP/DVP Website+Presentation/EV-Population-Insights/data/raw data/Electric_Vehicle_Population_Data.csv"

df = pd.read_csv(path)

print ("Number of rows and columns")
print(df.shape)

print("FIrst 10 rows")
df.head(10)

Number of rows and columns
(194232, 17)
FIrst 10 rows

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,1C4RJXN66R,Snohomish,Everett,WA,98204.0,2024,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,21.0,0.0,21.0,261311557,POINT (-122.2507211 47.8976713),PUGET SOUND ENERGY INC,5.306104e+10
1,KNDJX3AEXG,King,Renton,WA,98058.0,2016,KIA,SOUL,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,93.0,31950.0,11.0,210641315,POINT (-122.1476337 47.4438471),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
2,5YJ3E1EA3L,King,Seattle,WA,98125.0,2020,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,266.0,0.0,46.0,124517347,POINT (-122.304356 47.715668),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
3,1G1RC6S5XH,Kitsap,Port Orchard,WA,98367.0,2017,CHEVROLET,VOLT,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,53.0,0.0,26.0,7832933,POINT (-122.6530052 47.4739066),PUGET SOUND ENERGY INC,5.303509e+10
4,5UXTA6C09P,Snohomish,Monroe,WA,98272.0,2023,BMW,X5,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,30.0,0.0,39.0,235249262,POINT (-121.968385 47.854897),PUGET SOUND ENERGY INC,5.306105e+10
5,1FMCU0EZXN,Yakima,Moxee,WA,98936.0,2022,FORD,ESCAPE,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,38.0,0.0,15.0,197264322,POINT (-120.3552229 46.550869),PACIFICORP,5.307700e+10
6,5YJSA1DNXD,Thurston,Olympia,WA,98506.0,2013,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,208.0,69900.0,22.0,475076241,POINT (-122.86491 47.07503),PUGET SOUND ENERGY INC,5.306701e+10
7,1N4AZ0CP8F,Snohomish,Monroe,WA,98272.0,2015,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,84.0,0.0,39.0,187075577,POINT (-121.968385 47.854897),PUGET SOUND ENERGY INC,5.306105e+10
8,WP1AE2A21J,Snohomish,Everett,WA,98208.0,2018,PORSCHE,CAYENNE,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,14.0,0.0,44.0,122759276,POINT (-122.2032349 47.8956271),PUGET SOUND ENERGY INC,5.306104e+10
9,1N4BZ1BV4N,Snohomish,Everett,WA,98208.0,2022,NISSAN,LEAF,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,21.0,259974277,POINT (-122.2032349 47.8956271),PUGET SOUND ENERGY INC,5.306104e+10

In [19]:
df.columns.tolist()

df.dtypes

VIN (1-10)                                               str
County                                                   str
City                                                     str
State                                                    str
Postal Code                                          float64
Model Year                                             int64
Make                                                     str
Model                                                    str
Electric Vehicle Type                                    str
Clean Alternative Fuel Vehicle (CAFV) Eligibility        str
Electric Range                                       float64
Base MSRP                                            float64
Legislative District                                 float64
DOL Vehicle ID                                         int64
Vehicle Location                                         str
Electric Utility                                         str
2020 Census Tract                                    float64
dtype: object

In [20]:
df.isnull().sum()

VIN (1-10)                                             0
County                                                 9
City                                                   9
State                                                  0
Postal Code                                            9
Model Year                                             0
Make                                                   0
Model                                                  0
Electric Vehicle Type                                  0
Clean Alternative Fuel Vehicle (CAFV) Eligibility      0
Electric Range                                         2
Base MSRP                                              2
Legislative District                                 432
DOL Vehicle ID                                         0
Vehicle Location                                      13
Electric Utility                                       9
2020 Census Tract                                      9
dtype: int64

In [21]:
df.describe()

,Postal Code,Model Year,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,2020 Census Tract
count,194223.000000,194232.000000,194230.000000,194230.000000,193800.000000,1.942320e+05,1.942230e+05
mean,98175.800678,2020.781807,54.835458,978.730732,29.009954,2.248923e+08,5.297532e+10
std,2435.345863,2.999041,89.614355,7988.719011,14.901335,7.357830e+07,1.607770e+09
min,1731.000000,1997.000000,0.000000,0.000000,1.000000,4.385000e+03,1.001020e+09
25%,98052.000000,2019.000000,0.000000,0.000000,17.000000,1.872251e+08,5.303301e+10
50%,98125.000000,2022.000000,0.000000,0.000000,33.000000,2.339402e+08,5.303303e+10
75%,98372.000000,2023.000000,68.000000,0.000000,42.000000,2.601159e+08,5.305307e+10
max,99577.000000,2025.000000,337.000000,845000.000000,49.000000,4.792548e+08,5.602100e+10

In [22]:
df.drop(
    columns=[
        "VIN (1-10)",
        "State",
        "DOL Vehicle ID",
        "Legislative District",
        "2020 Census Tract"
    ],
    inplace=True
)

In [23]:
df.columns.tolist()

df.dtypes

County                                                   str
City                                                     str
Postal Code                                          float64
Model Year                                             int64
Make                                                     str
Model                                                    str
Electric Vehicle Type                                    str
Clean Alternative Fuel Vehicle (CAFV) Eligibility        str
Electric Range                                       float64
Base MSRP                                            float64
Vehicle Location                                         str
Electric Utility                                         str
dtype: object

In [24]:
df.isnull().sum()

County                                                9
City                                                  9
Postal Code                                           9
Model Year                                            0
Make                                                  0
Model                                                 0
Electric Vehicle Type                                 0
Clean Alternative Fuel Vehicle (CAFV) Eligibility     0
Electric Range                                        2
Base MSRP                                             2
Vehicle Location                                     13
Electric Utility                                      9
dtype: int64

In [25]:
missing_location = df[
    df["County"].isna() |
    df["City"].isna() |
    df["Postal Code"].isna()
]

display(missing_location)

,County,City,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Vehicle Location,Electric Utility
137,NaN,NaN,NaN,2018,CHEVROLET,VOLT,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,53.0,0.0,NaN,NaN
118698,NaN,NaN,NaN,2022,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,NaN,NaN
126041,NaN,NaN,NaN,2023,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,NaN,NaN
130949,NaN,NaN,NaN,2017,FORD,FUSION,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,21.0,0.0,NaN,NaN
135000,NaN,NaN,NaN,2017,TESLA,MODEL X,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,200.0,0.0,NaN,NaN
141297,NaN,NaN,NaN,2019,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,220.0,0.0,NaN,NaN
147117,NaN,NaN,NaN,2019,BMW,530E,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,16.0,53400.0,NaN,NaN
149153,NaN,NaN,NaN,2022,VOLVO,XC90,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,35.0,0.0,NaN,NaN
184137,NaN,NaN,NaN,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215.0,0.0,NaN,NaN

In [26]:
df = df.dropna(subset=["County", "City", "Postal Code"]).copy()

In [27]:
df.isnull().sum()

County                                               0
City                                                 0
Postal Code                                          0
Model Year                                           0
Make                                                 0
Model                                                0
Electric Vehicle Type                                0
Clean Alternative Fuel Vehicle (CAFV) Eligibility    0
Electric Range                                       2
Base MSRP                                            2
Vehicle Location                                     4
Electric Utility                                     0
dtype: int64

In [28]:
df = df.dropna(subset=["Vehicle Location"]).copy()

In [29]:
df.isnull().sum()

County                                               0
City                                                 0
Postal Code                                          0
Model Year                                           0
Make                                                 0
Model                                                0
Electric Vehicle Type                                0
Clean Alternative Fuel Vehicle (CAFV) Eligibility    0
Electric Range                                       2
Base MSRP                                            2
Vehicle Location                                     0
Electric Utility                                     0
dtype: int64

In [30]:
df.loc[
    df["Electric Range"].isna() | df["Base MSRP"].isna(),
    ["Model Year", "Make", "Model", "Electric Vehicle Type",
     "Electric Range", "Base MSRP"]
]

,Model Year,Make,Model,Electric Vehicle Type,Electric Range,Base MSRP
76822,2024,MERCEDES-BENZ,S-CLASS,Plug-in Hybrid Electric Vehicle (PHEV),NaN,NaN
186061,2024,MERCEDES-BENZ,S-CLASS,Plug-in Hybrid Electric Vehicle (PHEV),NaN,NaN

In [31]:
missing_rows = df[
    df["Electric Range"].isna() |
    df["Base MSRP"].isna()
]

for _, row in missing_rows.iterrows():

    print("\nMissing vehicle:")
    display(row[
        ["Model Year", "Make", "Model",
         "Electric Range", "Base MSRP"]
    ].to_frame().T)

    print("Matching vehicles:")

    matches = df[
        (df["Model Year"] == row["Model Year"]) &
        (df["Make"] == row["Make"]) &
        (df["Model"] == row["Model"])
    ]

    display(
        matches[
            ["Model Year", "Make", "Model",
             "Electric Range", "Base MSRP"]
        ]
        .drop_duplicates()
    )

Missing vehicle:

      Model Year           Make    Model Electric Range Base MSRP
76822       2024  MERCEDES-BENZ  S-CLASS            NaN       NaN

Matching vehicles:

       Model Year           Make    Model  Electric Range  Base MSRP
16264        2024  MERCEDES-BENZ  S-CLASS            46.0        0.0
76822        2024  MERCEDES-BENZ  S-CLASS             NaN        NaN

Missing vehicle:

       Model Year           Make    Model Electric Range Base MSRP
186061       2024  MERCEDES-BENZ  S-CLASS            NaN       NaN

Matching vehicles:

       Model Year           Make    Model  Electric Range  Base MSRP
16264        2024  MERCEDES-BENZ  S-CLASS            46.0        0.0
76822        2024  MERCEDES-BENZ  S-CLASS             NaN        NaN

In [32]:
mask = (
    (df["Model Year"] == 2024) &
    (df["Make"] == "MERCEDES-BENZ") &
    (df["Model"] == "S-CLASS") &
    (df["Electric Range"].isna())
)

df.loc[mask, "Electric Range"] = 46

In [33]:
df.isnull().sum()

County                                               0
City                                                 0
Postal Code                                          0
Model Year                                           0
Make                                                 0
Model                                                0
Electric Vehicle Type                                0
Clean Alternative Fuel Vehicle (CAFV) Eligibility    0
Electric Range                                       0
Base MSRP                                            2
Vehicle Location                                     0
Electric Utility                                     0
dtype: int64